version: '3'

services:
  traefik:
    image: traefik:v2.1
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=${CF_API_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.myresolver.acme.dnsChallenge.provider=cloudflare
      - --certificatesresolvers.myresolver.acme.dnsChallenge.delayBeforeCheck=0
      - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    labels:
      - "traefik.http.routers.http_catchall.rule=HostRegexp(`{any:.+}`)"
      - "traefik.http.routers.http_catchall.entrypoints=web"
      - "traefik.http.routers.http_catchall.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../dev/letsencrypt:/letsencrypt
    container_name: traefik

  service:
    build:
      context: ./
      dockerfile: momobackendDevDockerFile
    restart: always
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - APP_URL=${APP_URL}
      - TRAEFIK_API_URL=${TRAEFIK_API_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.routers.app.rule=Host(`${TRAEFIK_API_URL}`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.services.app.loadbalancer.server.port=3200"
    volumes:
      - ../../src/momobackend:/momobackend
    container_name: service
    entrypoint: ["sh","/keepup/docker-entrypoint.sh"]
      
  web:
    build:
      context: ./
      dockerfile: momoblogDevDockerFile
    restart: always
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_APP_URL=${REACT_APP_APP_URL}
      - REACT_APP_GOOGLE_CLIENT_ID=${REACT_APP_GOOGLE_CLIENT_ID}
      - REACT_APP_GOOGLE_CLIENT_SECRET=${REACT_APP_GOOGLE_CLIENT_SECRET}
      - REACT_APP_YAHOO_CLIENT_ID=${REACT_APP_YAHOO_CLIENT_ID}
      - REACT_APP_YAHOO_CLIENT_SECRET=${REACT_APP_YAHOO_CLIENT_SECRET}
      - TRAEFIK_APP_URL=${TRAEFIK_APP_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app2.tls.certresolver=myresolver"
      - "traefik.http.routers.app2.rule=Host(`${TRAEFIK_APP_URL}`)"
      - "traefik.http.routers.app2.entrypoints=websecure"
      - "traefik.http.services.app2.loadbalancer.server.port=3000"
    volumes:
      - ../../src/momoblog:/momoblog
    container_name: web
    entrypoint: ["sh","/keepup/docker-entrypoint.sh"]
      
  mysql:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ../dev/mysql:/var/lib/mysql
    container_name: mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: adminer